name: PrÃ¡ctica mÃ³dulo 2 ðŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ El trabajo fue activado automÃ¡ticamente por un ${{ github.event_name }} evento."      
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - uses: snok/install-poetry@v1
        with:
          version: 1.2.1
        
      - name: Test with pytest==7.1.2
        run: |
          pip install pytest
          pytest

      - name: Ejecutando Testing
        run: poetry run pytest
      - run: poetry build

      - name: Fichero del firectorio
        run: ls ${{ github.workspace }}

      - name: Publish to GH Release        
        uses: softprops/action-gh-release@v1