name: Pr치ctica m칩dulo 2 游
run-name: Pr치ctica m칩dulo 2 游
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "游꿀 El trabajo fue activado autom치ticamente por un ${{ github.event_name }} evento."      
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - uses: snok/install-poetry@v1
        with:
          version: 1.2.1
      
      - run: poetry install

      - name: Ejecutando Testing
        run: poetry run pytest

      - run: poetry build

      - name: Saluda mipaquete
        run: poetry run hola
